server:
  #统一前缀
  servlet:
    context-path: /mediinfo-springdemo
  port: 8000
  ssl:
    protocol: TLS
    key-store: classpath:keystore.p12
    key-store-password: 123456
  #1、 一定不要使用kill -9 操作，使用kill -2 来关闭容器。这样才会触发java内部ShutdownHook操作，kill -9不会触发ShutdownHook。
  #2、可以使用端点监控 POST 请求 /actuator/shutdown 来执行优雅关机。
  shutdown: graceful #开启优雅停机
java:
  starter:
    message: 第一个自定义starter
    enabled: true
javastack:
  name: java参数绑定实例
  user:
    - tansir
    - zhangsan
  params:
    tel: 17600159370
    address: 杭州余杭区
  security:
    key: ${random.uuid}
    code: ${random.long(0,100)}
member:
  name: tom
  sex: 1
  age: 32
  birthday: 2000-12-12 12:44:55
#swagger doc link: https://springdoc.org/index.html#properties
springdoc:
  openapi:
    Info:
      title: 文档标题
      description: swagger描述信息
      version: 1.0.0
      license:
        name: Apache 2.0
        url: http://springdoc.org
    externalDocs:
      description: SpringShop Wiki Documentation
      url: https://springshop.wiki.github.org/docs
  swagger-ui:
    enabled: true

spring:
  #激活的profile
  profiles:
    default: dev
    active: dev1,test
    #include: dev，test
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.19.125.100:3306/demo
    username: root
    password: admin123
  #jpa配置
  jpa:
    properties:
      hibernate:
        #根据类型可以生成特定的sql,https://docs.jboss.org/hibernate/orm/6.1/javadocs/org/hibernate/dialect/package-summary.html
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
  #日志
  logging:
    level:
      sql: debug
      root: debug
      #打印sql参数
      org.hibernate.SQL: debug
      org.springframework: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace
      org.hibernate.type.descriptor.sql.BasicExtractor: trace

#多文档示例
---
spring:
  config:
    activate:
      on-profile: dev1
---
spring:
  config:
    activate:
      on-profile: dev2
---
spring:
  profiles:
    #default: dev
    active: dev,pro #//可以通过命令行参数替换，默认是所有
    include: #//不会被替换，默认是空
        #- dev
        #- main
    group:
      dev:
        - dev1
        - dev2
